# Generated by Django 4.0.2 on 2022-02-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_additive_alter_watering_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='additives',
            field=models.ManyToManyField(to='main_app.Additive'),
        ),
    ]
